/**
  ******************************************************************************
  * @addtogroup     : App
  * @{
  * @file           : board_io.c
  * @brief          : Board IO functions
  * @author         : P.Kwekkeboom
  * @date           : Oct 09, 2023
  * @}
  ******************************************************************************
  */

#include "main.h"
#include "sys_app.h"

#include "../IO_Expander/IO_Expander.h"
#include "board_io.h"

struct_BoardIO_PinConfig stIO_PinConfig[]=
{
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOA, GPIO_PIN_0,    GPIO_NOPULL,  IO_INPUT,   IO_LOW_ACTIVE},  // INT_IO_MCU_IRQ_DETECT,
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOA, GPIO_PIN_1,    GPIO_NOPULL,  IO_OUTPUT,  IO_HIGH_ACTIVE}, // INT_IO_DEBUG_LED2
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOA, GPIO_PIN_4,    GPIO_NOPULL,  IO_OUTPUT,  IO_HIGH_ACTIVE}, // INT_IO_DEBUG_LED1
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOA, GPIO_PIN_15,   GPIO_NOPULL,  IO_INPUT,   IO_HIGH_ACTIVE}, // INT_IO_BOX_OPEN
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOA, GPIO_PIN_15,   GPIO_NOPULL,  IO_INPUT,   IO_HIGH_ACTIVE}, // INT_IO_VDD_TCXO_EXT
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOB, GPIO_PIN_5,    GPIO_NOPULL,  IO_OUTPUT,  IO_HIGH_ACTIVE}, // INT_IO_ADC_SELECT
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOB, GPIO_PIN_5,    GPIO_NOPULL,  IO_INPUT,   IO_LOW_ACTIVE},  // INT_IO_EXP_IRQ
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOB, GPIO_PIN_12,   GPIO_NOPULL,  IO_INPUT,   IO_HIGH_ACTIVE}, // INT_IO_3V3_DETECT
    { IO_INTERAL,   IO_EXPANDER_NONE, GPIOB, GPIO_PIN_13,   GPIO_NOPULL,  IO_OUTPUT,  IO_HIGH_ACTIVE}, // INT_IO_RF_SW_CTRL

    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_FRAM_CS,         0, IO_OUTPUT,  IO_LOW_ACTIVE  } ,  // EXT_IO_FRAM_CS
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_FLASH_SD_CS,     0, IO_OUTPUT,  IO_LOW_ACTIVE  } ,  // EXT_IO_FLASH_SD_CS
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_FLASH_NOR_CS,    0, IO_OUTPUT,  IO_LOW_ACTIVE  } ,  // EXT_IO_FLASH_NOR_CS
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_GE_EN,           0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_GE_EN
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_BOX_OPEN,        0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_BOX_OPEN
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_RST,             0, IO_OUTPUT,  IO_LOW_ACTIVE  } ,  // EXT_IO_RST
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_USB_CONNECTED,   0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_USB_CONNECTED
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_SENSOR_INTX,     0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SENSOR_INTX
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_BAT_ALERT,       0, IO_INPUT,   IO_LOW_ACTIVE  } ,  // EXT_IO_BAT_ALERT
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_VSENSOR_EN,      0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_VSENSOR_EN
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_VSYS_EN,         0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_VSYS_EN
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_VALWAYS_EN,      0, IO_OUTPUT,  IO_LOW_ACTIVE  } ,  // EXT_IO_VALWAYS_EN
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_DEBUG_SW1,       0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_DEBUG_SW1
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_DEBUG_SW2,       0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_DEBUG_SW2
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_SC_EN,           0, IO_OUTPUT,  IO_LOW_ACTIVE  } ,  // EXT_IO_SC_EN
    { IO_EXTERNAL,  IO_EXPANDER_SYS,  0,  1UL<<IO_EXP_RTC_PWR_EN,      0, IO_INPUT,   IO_LOW_ACTIVE  } ,  // EXT_IO_RTC_PWR_EN

    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_LOADSW1,     0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_LOADSW1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_LOADSW2,     0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_LOADSW2
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_SLOT1_GPIO0, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT1_GPIO0
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_SLOT1_GPIO1, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT1_GPIO1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_SLOT1_GPIO2, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT1_GPIO2
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_SLOT2_GPIO0, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT2_GPIO0
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_SLOT2_GPIO1, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT2_GPIO1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_SLOT2_GPIO2, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT2_GPIO2
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_INT1,        0, IO_INPUT,   IO_LOW_ACTIVE  } ,  // EXT_IO_INT1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_INT2,        0, IO_INPUT,   IO_LOW_ACTIVE  } ,  // EXT_IO_INT2
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_INT3,        0, IO_INPUT,   IO_LOW_ACTIVE  } ,  // EXT_IO_INT3
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_INT4,        0, IO_INPUT,   IO_LOW_ACTIVE  } ,  // EXT_IO_INT4
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_INT5,        0, IO_INPUT,   IO_LOW_ACTIVE  } ,  // EXT_IO_INT5
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_INT6,        0, IO_INPUT,   IO_LOW_ACTIVE  } ,  // EXT_IO_INT6
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_SPARE1,      0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_SPARE1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_INT,  0,  1UL<<IO_EXP_SPARE2,      0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_SPARE2

    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_LOADSW3,     0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_LOADSW3
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_LOADSW4,     0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_LOADSW4
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_LOADSW5,     0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_LOADSW5
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_LOADSW6,     0, IO_OUTPUT,  IO_HIGH_ACTIVE } ,  // EXT_IO_LOADSW6
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT3_GPIO0, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT3_GPIO0
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT3_GPIO1, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT3_GPIO1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT3_GPIO2, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT3_GPIO2
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT4_GPIO0, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT4_GPIO0
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT4_GPIO1, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT4_GPIO1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT4_GPIO2, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT4_GPIO2
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT5_GPIO0, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT5_GPIO0
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT5_GPIO1, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT5_GPIO1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT5_GPIO2, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT5_GPIO2
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT6_GPIO0, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT6_GPIO0
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT6_GPIO1, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT6_GPIO1
    { IO_EXTERNAL,  IO_EXPANDER_BUS_EXT,  0,  1UL<<IO_EXP_SLOT6_GPIO2, 0, IO_INPUT,   IO_HIGH_ACTIVE } ,  // EXT_IO_SLOT6_GPIO2
};
