name: Doxygen and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Run Doxygen
        run: |
          cd src
          doxygen P22296-10-SW.doxyfile

      - name: Deploy to GitHub Pages
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: src/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-to-github-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          directory: src/html
          target: /docs
