name: PlatformIO CI
on:
  push:
    branches:
      - main
      - v3
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Set Build Flags for Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "PLATFORMIO_BUILD_FLAGS=-DFW_VERSION_MAJOR=${GITHUB_REF#refs/tags/v*.*.*.} -DFW_VERSION_MINOR=${GITHUB_REF#refs/tags/v*.*.} -DFW_VERSION_PATCH=${GITHUB_REF#refs/tags/v*.} -DFW_VERSION_PROTO=0" >> $GITHUB_ENV

      - name: Set Build Flags for Main Branch
        if: github.ref == 'refs/heads/main'
        run: echo "PLATFORMIO_BUILD_FLAGS=-DFW_VERSION_PROTO=1" >> $GITHUB_ENV

      - name: Build PlatformIO Project
        run: pio run --build-flags ${{ env.BUILD_FLAGS }}

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/mfm_v3_m1284p/firmware.hex
            .pio/build/mfm_v3_m1284p/firmware.elf
